version: '3.8'

services:
  aurorabot:
    build: .
    container_name: aurorabot
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - aurora-network

networks:
  aurora-network:
    driver: bridge