services:
  voidbot:
    build: .
    container_name: voidbot
    restart: unless-stopped
    ports:
      - "3002:80"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - ./api:/app/api
      - ./commands:/app/commands
      - ./events:/app/events
      - ./internal:/app/internal
      - ./scripts:/app/scripts
      - ./config.yaml:/app/config.yaml
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - voidbot-network

networks:
  voidbot-network:
    driver: bridge


